libwww-perl/HTTP-Message

t/headers.t, t/response.t
There were only two places my quick grep found with indirect object notation.
=> got rid of some indirect object notation

lib/HTTP/Request.pm, lib/HTTP/Request/Common.pm, t/common-req.t
Hi, I would like to get PATCH method supported by HTTP::Request::Common
Hope the simple addition is reasonable, it works for me.
=> support PATCH HTTP method

.gitignore, .travis.yml, MANIFEST.SKIP, lib/HTTP/Message.pm, t/distmanifest.t, t/message.t
Better tests suite, travis and MANIFEST.SKIP.
This fixes merge conflicts in #27 submitted by @jeteve.
=> Avoid inconsistent setting of content to undef.

Changes, META.json, Makefile.PL, cpanfile, lib/HTTP/Request.pm, t/request.t
I ran into this issue today when I tried to GET a Mojo::URL object.  No
error was thrown until HTTP::Request tried to call the canonical()
method on the object.  So, just checking if an object provides a
scheme() method is not enough.
It's quite likely it should check for other methods as well, but this does fix this one particular case.
=> If an object is passed to HTTP::Request, it must provide a canonical()

lib/HTTP/Response.pm, t/response.t
=> Trim trailing \r from status line so message() doesn't return it.

Changes, lib/HTTP/Request.pm, lib/HTTP/Request/Common.pm
This question in [PerlMonks](http://perlmonks.org/index.pl?node_id=1204434) made us realize that there weren't really any example uses for the HTTP::Message family of modules. So, in order to begin to rectify that, this PR adds an EXAMPLES section in HTTP::Request which we can provide links to in other modules' documentation where necessary.
=> Add a few examples and show usage of ->add_part() for batch requests

t/message-old.t
Apply patch from https://rt.cpan.org/Public/Bug/Display.html?id=124526
=> Whenever possible, use an absolute four digit year for Time::Local

lib/HTTP/Status.pm
This updates the Status Codes to the official IANA Registry as described at:
https://www.iana.org/assignments/http-status-codes/http-status-codes.xhtml
I did remove a few that were not part of the official list, like `418: I'm a teapot`. But then again include some existing unofficial ones that were already in the old version in a separate module.
Maybe, in the future we can use an import like:
`use HTTP::Status ':nginx'`
to include the `444`, `495`, `496`, `497`, and `499`, for example.
=> Update status codes to official IANA list

lib/HTTP/Status.pm
Aligned the constants in the documentation with the implementation. Including minor cosmetic adjustments to the listing of constants in the documentation.
=> Corrections to the documentation

Changes, lib/HTTP/Status.pm, t/status-message.t
This fixes potential problems when new or unsupported status codes
are used by adding a default status code.
This change also adds tests.
=> Add default status_message for unknown status codes (GH#105)

Changes, lib/HTTP/Response.pm, t/response.t
Fixes <https://github.com/libwww-perl/HTTP-Message/issues/86>.
Rewrites `HTTP::Response->filename` method:
- Use `Try::Tiny` instead of `eval` block.
- Assign capturing groups using list context.
- Make documentation explicit that the encoding is `locale_fs`.
- Run Perltidy on `filename` method.
HTTP::Response test:
- RFC 8187 tests require the `utf8` pragma to ensure that the test file
is read as UTF-8.
=> Add support for RFC 8187 encoded filenames

.gitignore
Leading `**/`, trailing `**/`, and `/**/` are the only valid uses of `**` in git globs.
=> Fix gitignore wildcard

lib/HTTP/Response.pm, t/response.t
fix #124
Setting LC_ALL=C reveals that HTTP::Response::filename created unusable file
names. Use Encode's fallback coderef to make a URI encoded name when the plain
character does not work. Practice with dwheeler's encodef has shown this is
the least interference-prone encoding scheme.
=> try hard to make a usable file name

lib/HTTP/Request.pm
The examples for simple and batch POST request show
`encode_utf8(encode_json(...))` which will produce double-encoded UTF-8.
`encode_json()` produces bytes, not characters, so the result should not
be run through `encode_utf8()`
=> Fix JSON request encoding examples in POD

lib/HTTP/Request/Common.pm, t/common-req.t
As HTTP::Request support OPTIONS as well, this will be very helpful to be exported by HTTP::Request::Common as well
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS
=> Support OPTIONS request method

Changes, dist.ini, lib/HTTP/Headers.pm, t/headers.t, t/lib/Secret.pm
To avoid leaking secrets in stack traces, my team has started passing
secrets as blessed coderefs, similar to Secret.pm in this commit. One of
the spots we have a secret is in a header value.
I found that passing such an object to HTTP::Headers sort of works
already, but when LWP tries to use it in the request it calls clone()
which fails due to Storable throwing "Can't store CODE items".
Instead, this changes us to use Clone::clone which seems to provide
similar functionality while supporting this use case.
I'm not sure if there's important functional implications though between Storable and Clone.
Thank you!
=> Support non-string header values that stringify

lib/HTTP/Status.pm, t/status.t
The first commit fixes several status descriptions to match the canonical IANA list, and adds backcompat constants and tests for these renames, as well as a backcompat HTTP_NO_CODE constant that was missed in #100.
The second commit adds 425 Too Early and backcompat constants for the previous unofficial names, as it is now an official IANA status code from RFC 8470.
=> Fix HTTP status descriptions and add 425 Too Early

Changes, lib/HTTP/Request/Common.pm
After HTTP-Message 6.31 (#156), t/common-req.t fails on MSWin32.
```
$ prove -bv t/common-req.t
(...snip...)
#
#
#
ok 43
ok 44
ok 45
ok 46
not ok 47
```
https://github.com/libwww-perl/HTTP-Message/blob/161ef4be44b581419f09f38e7a9df4ac598abfdc/t/common-req.t#L157
On other UNIX-like platforms, filename (`$form_file`) is not full path but file name only. To do the same behavior and fix the test failure, I have used File::Spec in this pull request. But it is only for MSWin32 and needs to add File::Spec as runtime prereqs. I'm not sure if this is a reasonable approach.
=> Use File::Spec for MSWin32 on Content-Disposition filename

Changes, lib/HTTP/Message.pm, t/message.t
This pull request allows `can` method of `HTTP::Message` to return a code reference for a method that is delegated to `HTTP::Headers` even if that method is not yet called.
Fixes #158
=> Allow `can` method to respond to delegated methods

lib/HTTP/Headers/Util.pm, t/headers-util.t
Closes #167.  I think this is pretty straightforward.  When looking for `name=value`, the regexes miss the case where both are the empty string, that is, a bare `=` is in the header, which causes the function to fall through to the `die`.  I actually encountered such a header in the wild, bizarre though it may be.  This PR prevents an error by simply skipping over the `=` in this case.
=> Catch case of empty name/value in header words split.

lib/HTTP/Message.pm
In response to [this comment](https://github.com/libwww-perl/HTTP-Message/pull/99#issuecomment-954863759), this PR updates the documentation for decoded_content to clarify the behavior regarding character set decoding of "textual" content.
=> Clarify documentation for decoded_content

Changes, lib/HTTP/Request/Common.pm
this is straightforward, but a double-check would be appreciated :)
=> HTTP::Request::Common does not put headers in an arrayref, unlike HTTP::Request

.github/workflows/build-and-test.yml, .gitignore, Changes, dist.ini, lib/HTTP/Message.pm, t/message-brotli.t
I've taken #164 and added tests. I've also included encoding for Brotli, as we support this for other compressions.
However, I am not sure how to proceed with the dependencies. I made IO::Compress::Brotli and IO::Uncompress::Brotli (both are [from the same dist](https://metacpan.org/pod/IO::Compress::Brotli)) _suggests_ similar to Clone, but we require all of them for testing. The problem is that IO::Compress::Brotli requires Perl 5.14, so our github action for 5.10 and 5.12 would break.
I'm unsure how to proceed without causing breakage, so I've marked this as draft for now.
Closes #164 
Fixes #163
=> Extension of #164 with tests

Changes, t/headers-auth.t, t/response.t
Saves needing to manually prefix the messages for TAP and is more idiomatic.
=> Replace "print" with "note" in tests

Changes, lib/HTTP/Request/Common.pm
Retroactively added a note in the Changes section for 6.21, and added note to doc for OPTIONS in HTTP::Request::Common
This addresses #177
=> Noted that OPTIONS http method support was added in 6.21

Changes, lib/HTTP/Status.pm, t/status.t
This addresses #160 by
* Adding an example to the doc for status_message(), to make clear what it returns
* Added a new function `status_constant_name()`, which maps (404) to `"HTTP_NOT_FOUND"` (added some tests in t/status.t)
=> Added status_constant_name() and clarified what status_message() returns

Changes, lib/HTTP/Response.pm, t/response.t
A change to HTTP::Response to not look at Content-Location when deciding the base URI.
RFC 7231 says:
The definition of Content-Location has been changed to no longer
affect the base URI for resolving relative URI references, due to
poor implementation support and the undesirable effect of potentially
breaking relative links in content-negotiated resources.
This change was originally suggested by Toby Inkster in 2012 on RT, and ported over to #51
=> don't consider Content-Location when determining the base URI GH#51

Changes, lib/HTTP/Request/Common.pm, t/common-req.t
This bumps the max buffer size for `read()` to 8192 from 2048, and also made it a package variable,
rather than hard-coded in-line.
This was suggested by a user, who said it gave "much better performance", in 2015.
RT#105184 ported over to #59
=> Increased read() buffer size from 2048 to 8192, when reading form data

Changes, dist.ini, lib/HTTP/Headers.pm
This addresses GH#64, changing HTTP::Headers to rely on Clone to provide the `clone()` method.
=> Always rely on Clone::clone() as the provider of HTTP::Headers::clone()

lib/HTTP/Headers.pm
Clone is an Exporter. HTTP::Headers should not be an Exporter.
=> import clone from Clone rather than inheriting

Changes, lib/HTTP/Status.pm, t/status.t
This is a cherry pick and squash of #34 (2016), which in turn is a rework of #4 (2013).
It would be great to merge this before it turns 10 in February. 😢 
Closes #34.
=> add the 'status_code' function for getting all status codes as hash

lib/HTTP/Status.pm, t/status.t
* 306 is officially reserved but unused
* 413 is called 'Content Too Large' in RFC 9110
* 418 is officially reserved, so let's make it official here too
* 422 is imported from WebDAV and named 'Unprocessable Content'.
Reference: https://www.rfc-editor.org/rfc/rfc9110.html#name-changes-from-rfc-7231
=> Update several status codes to RFC 9110

lib/HTTP/Status.pm, t/headers.t, t/response.t
I found a few small minor typos.
=> Fix few minor typos
